AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL free tier"

Parameters:
  ProjectName:
    Type: String
    Default: ecommerce
  DBPassword:
    Type: String
    NoEcho: true

Resources:

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Private subnets for RDS"
      SubnetIds:
        - !ImportValue ecommerce-private-subnet-1
        - !ImportValue ecommerce-private-subnet-2
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: !Sub "${ProjectName}-db"
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: "8.0"
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      DBName: ecommerce
      AllocatedStorage: "20"
      StorageType: gp2
      MultiAZ: false
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !ImportValue ecommerce-rds-sg
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 0
      DeletionProtection: false
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  DBEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub "${ProjectName}-db-endpoint"
  DBPort:
    Value: !GetAtt DBInstance.Endpoint.Port
    Export:
      Name: !Sub "${ProjectName}-db-port"
